credits/urls.py
from django.conf.urls import url
from django.conf import settings
from django.views.generic import RedirectView
from credits.views import WalletView, GetCreditsView, StripeWebhookView, CheckIntentView, RefundView

# If Stripe API key exists use the default urls, otherwise redirect them to the home page.
if settings.STRIPE_SECRET:
    urlpatterns = [
        url(r'^$', WalletView.as_view(), name='wallet'),
        url(r'^get/$', GetCreditsView.as_view(), name='get_credits'),
        url(r'^refund/$', RefundView.as_view(), name='refund_credits'),
        url(r'^webhook/$', StripeWebhookView.as_view(), name='stripe_webhook'),
        url(r'^payment-success/(?P<pk>[0-9]+)/$', CheckIntentView.as_view(), name='check_intent'),
    ]
else:
    urlpatterns = [
        url(r'^$', RedirectView.as_view(url='/'), name='wallet'),
        url(r'^get/$', RedirectView.as_view(url='/'), name='get_credits'),
        url(r'^refund/$', RedirectView.as_view(url='/'), name='refund_credits'),
    ]

issue_tracker/urls.py
import os
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from django.conf import settings
from account import urls as account_urls
from tickets import urls as tickets_urls
from credits import urls as credits_urls
from stats import urls as stats_urls
from stats.views import IndexView, RoadmapView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include(account_urls)),
    url(r'^tickets/', include(tickets_urls)),
    url(r'^credits/', include(credits_urls)),
    url(r'^stats/', include(stats_urls)),
    url(r'^roadmap/$', RoadmapView.as_view(), name='roadmap'),
    url(r'^$', IndexView.as_view(), name='index'),
]

# If local static is set, or there is no AWS access key use local media storage
if 'LOCAL_STATIC' in os.environ or not settings.AWS_ACCESS_KEY_ID:
    urlpatterns.append(url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}))

stats/urls.py
from django.conf.urls import url
from stats.views import TicketStatsView, AllTicketStatsView, TransactionsStatsView

urlpatterns = [
    url(r'^$', AllTicketStatsView.as_view(), name='all_ticket_stats'),
    url(r'^(?P<pk>[0-9]+)/$', TicketStatsView.as_view(), name='ticket_stats'),
    url(r'^transactions/$', TransactionsStatsView.as_view(), name='transaction_stats'),
]

credits/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.utils import timezone
from datetime import timedelta
import stripe

stripe.api_key = settings.STRIPE_SECRET

# Create your models here.


class Wallet(models.Model):
    '''
    Class to keep track of a user's credits.
    '''
    user = models.OneToOneField(User)
    balance = models.IntegerField(default=0)

    class Meta:
        # Permissions to prevent admins having a wallet, and allow an admin to view transaction stats.
        permissions = (('cant_have_wallet', 'User can\'t have a wallet.'),
                       ('can_view_transactions_stats', 'User can view all transaction stats'))

    def __str__(self):
        return '{}\'s wallet'.format(self.user.username)

    def credit(self, amount=0, real_value=0, transaction_id=None):
        '''
        Credits the user's wallet with an amount, logs it and associates the transaction with a real value, and a Stripe transaction.
        '''
        self.balance += amount
        transaction = Credit.objects.create(wallet=self, amount=amount, real_value=real_value, stripe_transaction_id=transaction_id)
        transaction.save()
        self.save()
        return self.balance

    def debit(self, amount=0, real_value=0):
        '''
        Debits an amount from the users wallet and logs it.
        '''
        if self.balance >= amount:
            self.balance -= amount
            transaction = Debit.objects.create(wallet=self, amount=amount, real_value=real_value)
            transaction.save()
            self.save()
            return transaction
        else:
            return False


class Transaction(models.Model):
    '''
    Abstract class for a transaction.
    '''
    wallet = models.ForeignKey(Wallet)
    created = models.DateTimeField(auto_now_add=True)
    amount = models.IntegerField(default=0)
    real_value = models.IntegerField(default=0)

    class Meta:
        abstract = True


class Credit(Transaction):
    '''
    A model to log credits to a user's wallet, store it's Stripe transaction id and track whether it has been refunded.
    '''
    refunded = models.BooleanField(default=False)
    stripe_transaction_id = models.CharField(max_length=50, null=True, default=None)

    def __str__(self):
        return '{} Credits to {} @ {}'.format(self.amount, self.wallet.user, self.created.strftime('%d/%m/%y %H:%M'))

    @property
    def can_refund(self):
        '''
        Returns whether or not a credit can be refunded.
        '''
        return not self.refunded and self.wallet.balance >= self.amount\
            and self.created > timezone.now() - timedelta(days=90) and self.stripe_transaction_id is not None

    def refund(self):
        '''
        Refunds a credit transaction, debiting the user's wallet the amount and refunding the Stripe transaction.
        '''
        if self.can_refund:
            try:
                refund = stripe.Refund.create(charge=self.stripe_transaction_id)
                if refund['status'] == 'succeeded':
                    self.wallet.debit(self.amount, refund['amount'])
                    self.refunded = True
                    self.save()
                    return (refund['status'], refund['amount'])
                else:
                    return (False, 0)
            except stripe.error.StripeError:
                return (False, 0)
        else:
            return (False, 0)


class Debit(Transaction):
    '''
    Model to log debits.
    '''
    def __str__(self):
        return 'Debit of {} Credits From {} @ {}'.format(self.amount, self.wallet.user, self.created)


class PaymentIntentManager(models.Manager):
    def create_payment_intent(self, user, credits, amount):
        '''
        Reuses or creates a payment intent for a new transaction.
        '''
        try:
            payment_intent = self.get(user=user, complete=False)
            payment_intent.update(credits, amount)
        except PaymentIntent.DoesNotExist:
            stripe_payment_intent = stripe.PaymentIntent.create(amount=amount, currency=settings.STRIPE_CURRENCY)
            intent_id = stripe_payment_intent.id
            payment_intent = self.create(user=user, intent_id=intent_id, credits=credits, amount=amount)

        payment_intent.save()
        return payment_intent


class PaymentIntent(models.Model):
    '''
    Model to associate a Stripe payment intent with a prospective transaction.
    '''
    user = models.ForeignKey(User)
    intent_id = models.CharField(max_length=100)
    credits = models.IntegerField(default=0)
    amount = models.IntegerField(default=0)
    complete = models.BooleanField(default=False)

    objects = PaymentIntentManager()

    def retrieve_intent(self):
        '''
        Retrives the actual payment intent from Stripe
        '''
        return stripe.PaymentIntent.retrieve(self.intent_id)

    @property
    def client_secret(self):
        '''
        Returns the client secret from for the payment intent to be used by the stripe.js api to take payment.
        '''
        intent = self.retrieve_intent()
        return intent.client_secret

    def update(self, credits=0, amount=0):
        '''
        Updates the payment intent, both in the DB and in Stripe.
        '''
        stripe.PaymentIntent.modify(self.intent_id, amount=amount)
        self.credits = credits
        self.amount = amount
        self.save()

    def fulfill(self):
        '''
        Completes the payment, checks the correct amount has been recieved, and
        credits the users wallet the correct number of credits.
        '''
        intent = self.retrieve_intent()
        if intent.amount_received == self.amount == intent.charges.data[0].amount:
            wallet = Wallet.objects.get_or_create(user=self.user)[0]
            wallet.credit(self.credits, self.amount, intent.charges.data[0].id)
            self.complete = True
            self.save()
        return self.complete

credits/forms.py
from django import forms


class GetCreditsForm(forms.Form):
    no_credits = forms.IntegerField(min_value=1, initial=10, label='Number of credits to buy:')

credits/views.py
from django.views.generic.base import TemplateView, View, ContextMixin
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.conf import settings
from django.http import HttpResponse
from django.core.exceptions import PermissionDenied
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from datetime import timedelta
import json
from credits.forms import GetCreditsForm
from credits.models import PaymentIntent, Credit
import stripe

stripe.api_key = settings.STRIPE_SECRET

# Create your views here.


class HasWalletMixin(LoginRequiredMixin, UserPassesTestMixin):
    '''
    Ensures the user has a wallet to access (for instance members of the dev team don't want/need a wallet).
    As super users have all permissions by default this will automatically apply to them.
    '''
    raise_exception = True

    def test_func(self):
        return not self.request.user.has_perm('credits.cant_have_wallet')


class WalletView(HasWalletMixin, TemplateView):
    '''
    Wallet view. Uses the existing wallet_amount context variable.
    '''
    template_name = 'wallet.html'


class GetCreditsView(HasWalletMixin, FormView, ContextMixin):
    '''
    View for users to buy credits.
    '''
    template_name = 'get_credits.html'
    form_class = GetCreditsForm
    cost_per_credit = 60

    def get_context_data(self, **kwargs):
        context = super(GetCreditsView, self).get_context_data(**kwargs)
        context['cost_per_credit'] = '{:.2f}'.format(self.cost_per_credit / 100)
        return context

    def form_valid(self, form):
        '''
        Once the user chooses an amount, a payment intent is created, and the payment page with the Stripe.js API is returned.
        Overrides success url redirect.
        '''
        no_credits = form.cleaned_data['no_credits']
        charge = no_credits * self.cost_per_credit
        intent = PaymentIntent.objects.create_payment_intent(user=self.request.user, credits=no_credits, amount=charge)
        intent.save()
        return render(self.request, 'get_credits_pay.html',
                      {'client_secret': intent.client_secret, 'stripe_publishable': settings.STRIPE_PUBLISHABLE,
                       'charge': '{:.2f}'.format(charge / 100), 'no_credits': no_credits, 'intent_db_id': intent.id})


class RefundView(HasWalletMixin, SingleObjectMixin, TemplateView, View):
    '''
    View to refund a users latest transaction, if they have at least that many credits remaining.
    '''
    template_name = 'refund.html'
    http_method_names = ['get', 'post']
    context_object_name = 'transaction'

    def get_object(self, queryset=None):
        '''
        Gets the most recent unrefunded transaction.
        '''
        last_90_days = timezone.now().date() - timedelta(days=90)
        try:
            self.object = self.request.user.wallet.credit_set.filter(refunded=False, real_value__gte=1, created__gt=last_90_days).order_by('-created')[0]
        except Credit.DoesNotExist:
            self.object = None

        return self.object

    def get_context_data(self, **kwargs):
        self.get_object()
        context = super(RefundView, self).get_context_data(**kwargs)
        if self.object:
            context['refund_value'] = '£{:.2f}'.format(self.object.real_value / 100)

        return context

    def post(self, request):
        self.get_object()
        if self.object and self.object.can_refund:
            success, amount = self.object.refund()
            if success:
                messages.success(self.request, 'Successfully refunded £{:.2f}'.format(amount / 100))
            else:
                messages.error(self.request, 'Failed to refund transaction.')
            return redirect(reverse_lazy('wallet'))
        else:
            return self.get(request)


class CheckIntentView(LoginRequiredMixin, SingleObjectMixin, View):
    '''
    View to poll payment intents for completion.
    '''
    model = PaymentIntent
    http_method_names = ['get']

    def get(self, request, pk):
        intent = self.get_object()
        if intent.user != request.user:
            raise PermissionDenied()
        if intent.complete:
            messages.success(self.request, 'Payment successful.')
        response = {'success': intent.complete}
        return HttpResponse(json.dumps(response), content_type='application/json')


class StripeWebhookView(View):
    '''
    View to provide webhook for Stripe payment events.
    '''
    http_method_names = ['post']

    @method_decorator(csrf_exempt)  # View needs to be CSRF exmpt to allow Stripe to send POST requests.
    def dispatch(self, request, *args, **kwargs):
        return super(StripeWebhookView, self).dispatch(request, *args, **kwargs)

    def post(self, request):
        '''
        Checks validity of posted payment event json and deals with it as apropriate.
        '''
        payload = request.body

        try:
            event = stripe.Event.construct_from(json.loads(payload), stripe.api_key)
        except (ValueError, stripe.error.SignatureVerificationError):
            # Invalid payload or invalid signature
            return HttpResponse(status=400)

        event_dict = event.to_dict()

        if event_dict['type'] == "payment_intent.succeeded":
            # If the event is a successful payment, match it to a stored intent object, and fulfill the payment.
            intent = event_dict['data']['object']
            try:
                payment_intent = PaymentIntent.objects.get(intent_id=intent['id'])
                payment_intent.fulfill()
            except PaymentIntent.DoesNotExist:
                # If the payment intent doesn't exist in the system, something needs to be done by a human being...
                # Payment has been made, but the order cannot be fulfilled. Payment probably needs refunding.
                print('Payment succeded, but failed to find payment intent in tracker DB.')

        return HttpResponse(status=200)

credits/templates/get_credits.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Get Credits{% endblock %}
{% block content %}
<section class="content row">
    <div class="col-12">
        <h1>Get Credits</h1>
        <form method='POST'>
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <div class="text-center">
                <button type="submit" class="btn btn-primary w-75">
                    Buy <span id="no-credits"></span> credit<span id="credit-plural"></span> for £<span id="cost"></span>
                </button>
            </div>
            {% endbuttons %}
        </form>
    </div>
</section>
{% endblock %}
{% block javascript %}
<script>
    const costPerCredit = {{ cost_per_credit }};

    function calculateCost() {
        let noCredits = $('#id_no_credits').val();
        let plural = noCredits != 1 ? 's' : '';
        let cost = noCredits * costPerCredit;
        $('#no-credits').text(noCredits);
        $('#credit-plural').text(plural);
        $('#cost').text(cost.toFixed(2));
    }

    $(function() {
        calculateCost();

        $('#id_no_credits').on('change', calculateCost);
    });
</script>
{% endblock %}

credits/templates/get_credits_pay.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Get Credits - Pay{% endblock %}
{% block content %}
<section class="content row">
    <div class="col-12">
        <h1>Get Credits - Pay</h1>
        <h2>Buying {{ no_credits }} credits for £{{ charge }}</h2>
        <form id="payment-form" data-secret="{{ client_secret }}">
            <div class="row">
                <div class="col-12">
                    <div class="form-group">
                        <label for="card-number"><i class="far fa-credit-card"></i> Credit or debit card number:</label>
                        <div id="card-number" class="form-control" style='height: 2.4em; padding-top: .7em;'></div>
                    </div>
                </div>
                <div class="col-12 col-sm-6">
                    <div class="form-group">
                        <label for="card-expiry">Expires:</label>
                        <div id="card-expiry" class="form-control" style='height: 2.4em; padding-top: .7em;'></div>
                    </div>
                </div>
                <div class="col-12 col-sm-6">
                    <div class="form-group">
                        <label for="card-cvc">CVC:</label>
                        <div id="card-cvc" class="form-control" style='height: 2.4em; padding-top: .7em;'></div>
                    </div>
                </div>
                <div class="col-12 text-center">
                    {% buttons %}
                    <button type="submit" class="btn btn-primary w-75">Pay £{{ charge }} now</button>
                    {% endbuttons %}
                </div>
            </div>

            <div class="alert alert-warning">
                <p>Use payment intents testing cards:</p>
                <ul>
                    <li>Use: 4000002500003155 to continue to verification</li>
                    <li>Use: 4000008260003178 to continue to verification, but fail with insufficient funds</li>
                </ul>
            </div>
            
        </form>
        <!-- Modal to display payment error messages -->
        <div class="modal" id="payment-error-modal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Payment failed</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p id="payment-error-message">Something went wrong with the payment.</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- Model to display payment processing spinner -->
        <div class="modal" id="payment-processing-modal" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Processing Payment...</h5>
                    </div>
                    <div class="modal-body">
                        <div class="text-center">
                            <div class="spinner-border m-5" role="status">
                                <span class="sr-only">Processing...</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block javascript %}
<script>
    function handlePaymentResponse(result) {
        if (result.error) {
            // If stripe returns a failure, show the user the message from stripe in a modal and allow them to retry.
            $('#payment-error-message').text(result.error.message);
            $('#payment-processing-modal').modal('hide');
            $('#payment-error-modal').modal('show');
        }else if (result.paymentIntent && result.paymentIntent.status === 'succeeded') {
            // If stripe returns success, poll the database until the stripe webhook has updated the user's wallet.
            pollPaymentComplete(1000);
        }
    }

    function pollPaymentComplete(delay) {
        $.get('{% url "check_intent" pk=intent_db_id %}', function(data) {
            if (data.success) window.location.replace('{% url "wallet" %}');
            else pollPaymentComplete(delay)
        }).fail(function() {pollPaymentComplete(delay)});
    }

    $(function() {
    	// On load set up stripe API and create Stripe Elements card input.
        let stripe = Stripe('{{ stripe_publishable }}');

        let elements = stripe.elements();
        let cardNumberElement = elements.create('cardNumber');
        cardNumberElement.mount('#card-number');

        let cardExpiryElement = elements.create('cardExpiry');
        cardExpiryElement.mount('#card-expiry');

        let cardCvcElement = elements.create('cardCvc');
        cardCvcElement.mount('#card-cvc');

        $('#payment-form').on('submit', function(e) {
            // On payment submission prevent the form being submitted, 
            // retrieve the payment intent client secret key and pass to Stripe with the card details.
            e.preventDefault();
            $('#payment-processing-modal').modal('show');
            let clientSecret = $('#payment-form').data('secret');
            stripe.handleCardPayment(clientSecret, cardNumberElement)
                  .then(handlePaymentResponse);
        });
    });   
</script>
{% endblock %}

credits/templates/refund.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Refund last transaction{% endblock %}
{% block content %}
<section class="content row">
    <div class="col-12">
{% if transaction is not None %}
    {% if transaction.can_refund %}
        <h1>Refund {{ transaction.amount }} credits for {{ refund_value }}</h1>
        <p>On {{ object.created|date:'d/m/y H:i' }}</p>
        <p>You can refund your last transaction up to 90 days after making the payment. Refunds will take between 5 and 10 days business days to appear on your statment</p>
        <form method="POST">
            {% csrf_token %}
            {% buttons %}
            <button type="submit" class="btn btn-primary">Request Refund</button>
            {% endbuttons %}
        </form>
    {% else %}
        <h1>Insufficient credits to refund last transaction</h1>
        <p>You have spent some or all of the credits purchased in your last transaction, and are no longer eligible for a refund.</p>
    {% endif %}
{% else %}
        <h1>No transactions to refund</h1>
        <p>There are no recent transactions eligible to refund.</p>
{% endif %}
    </div>
</section>
{% endblock %}

credits/templates/wallet.html
{% extends "base.html" %}
{% block title %}Your Credits{% endblock %}
{% block content %}
<section class="content row">
    <div class="col-12">
        <h1>Credits: {{ wallet_balance }}</h1>
        <p>You can use credits to vote for new features. Spending credits is a great way to support the development of Unicorn Attractor, while also having your say in the direction the game takes.</p>
        <a href="{% url 'get_credits' %}" class="btn btn-primary">Get more credits</a>
        <a href="{% url 'refund_credits' %}" class="btn btn-warning">Request Refund</a>
    </div>
</section>
{% endblock %}